### ISSUE TITLE
Нужно сделать блоку dropdown_menu overfow hidden чтобы скругления остовались 

### ISSUE THREAD

**Issue by vladorod** [vladorod/Calculator#1]
https://github.com/vladorod/Calculator/blob/90cbae01451c2ce181732e3409a3d3d7a7fd0a28/index.html#L17

**Comment by vladorod** [comment]
Баг остался: 
 
![msedge_W0Ah4eLAnV](https://github.com/vladorod/Calculator/assets/34486493/caba7b9b-a44c-44ef-9ab8-ea5f4ee2a709)

**Comment by vladorod** [comment]
Поправить нужно на всех элементах

**Comment by vladorod** [comment]
@Bigger134

**Comment by Bigger134** [comment]
@vladorod сделал обёртку внутри меню, поправил баг
