### ISSUE TITLE
Сосок в макете меньше, можешь померить его там с помощью создания квадрата в pxio 

### ISSUE THREAD

**Issue by vladorod** [vladorod/Calculator#2]
https://github.com/vladorod/Calculator/blob/90cbae01451c2ce181732e3409a3d3d7a7fd0a28/src/style.css#L161C1-L171

**Comment by vladorod** [comment]
@Bigger134 Отпишись как поправишь

**Comment by Bigger134** [comment]
@vladorod померил, исправил на 6px
